#if !defined(WARNINGS_H)
#define WARNINGS_H

#include "platform_detection.h"

#if !defined(DEBUGGING)
#define DEBUGGING 0
#endif

#if !defined(TESTING)
#define TESTING 0
#endif

#if CBASE_CRT_MSVC
  #pragma warning(push, 4)
#endif

#if CC_GCC
  // -Wall
  #pragma GCC diagnostic error "-Waddress"
  #pragma GCC diagnostic error "-Warray-bounds"
  #pragma GCC diagnostic error "-Wbool-compare"
  #pragma GCC diagnostic error "-Wbool-operation"
  #pragma GCC diagnostic error "-Wchar-subscripts"
  #pragma GCC diagnostic error "-Wcomment"
  #pragma GCC diagnostic error "-Wformat"
  #pragma GCC diagnostic error "-Wformat-overflow"
  #pragma GCC diagnostic error "-Wformat-truncation"
  #pragma GCC diagnostic error "-Wint-in-bool-context"
  #pragma GCC diagnostic error "-Wlogical-not-parentheses"
  #pragma GCC diagnostic error "-Wmain"
  #pragma GCC diagnostic error "-Wmaybe-uninitialized"
  #pragma GCC diagnostic error "-Wmemset-elt-size"
  #pragma GCC diagnostic error "-Wmemset-transposed-args"
  #pragma GCC diagnostic error "-Wmisleading-indentation"
  #pragma GCC diagnostic error "-Wmissing-attributes"
  #pragma GCC diagnostic error "-Wmissing-braces"
  #pragma GCC diagnostic error "-Wmultistatement-macros"
  #pragma GCC diagnostic error "-Wnonnull"
  #pragma GCC diagnostic error "-Wnonnull-compare"
  #pragma GCC diagnostic error "-Wparentheses"
  #pragma GCC diagnostic error "-Wpointer-sign"
  #pragma GCC diagnostic error "-Wrestrict"
  #pragma GCC diagnostic error "-Wreturn-type"
  #pragma GCC diagnostic error "-Wsequence-point"
  #pragma GCC diagnostic error "-Wsizeof-pointer-div"
  #pragma GCC diagnostic error "-Wsizeof-pointer-memaccess"
  #pragma GCC diagnostic error "-Wstrict-aliasing"
  #pragma GCC diagnostic error "-Wstrict-overflow"
  #pragma GCC diagnostic error "-Wstringop-overflow"
  #pragma GCC diagnostic error "-Wstringop-truncation"
  #pragma GCC diagnostic error "-Wswitch"
  #pragma GCC diagnostic error "-Wswitch-bool"
  #pragma GCC diagnostic error "-Wtautological-compare"
  #pragma GCC diagnostic error "-Wtrigraphs"
  #pragma GCC diagnostic error "-Wuninitialized"
  #pragma GCC diagnostic error "-Wunknown-pragmas"
  #pragma GCC diagnostic error "-Wunused-function"
  #pragma GCC diagnostic error "-Wunused-label"
  #pragma GCC diagnostic error "-Wunused-value"
  #pragma GCC diagnostic error "-Wunused-variable"
  #pragma GCC diagnostic error "-Wvolatile-register-var"

  // -Wextra
  #pragma GCC diagnostic error "-Wclobbered"
  #pragma GCC diagnostic error "-Wcast-function-type"
  #pragma GCC diagnostic error "-Wempty-body"
  #pragma GCC diagnostic error "-Wignored-qualifiers"
  #pragma GCC diagnostic error "-Wimplicit-fallthrough"
  #pragma GCC diagnostic error "-Wmissing-field-initializers"
  #pragma GCC diagnostic error "-Wmissing-parameter-type"
  #pragma GCC diagnostic error "-Wold-style-declaration"
  #pragma GCC diagnostic error "-Woverride-init"
  #pragma GCC diagnostic error "-Wsign-compare"
  #pragma GCC diagnostic error "-Wstring-compare"
  #pragma GCC diagnostic error "-Wtype-limits"
  #pragma GCC diagnostic error "-Wshift-negative-value"
  #pragma GCC diagnostic error "-Wunused-parameter"
  #pragma GCC diagnostic error "-Wunused-but-set-parameter"

  // Enabled by default or not enabled -Wall or -Wextra
  #pragma GCC diagnostic error "-WNSObject-attribute"
  #pragma GCC diagnostic error "-Waddress-of-packed-member"
  #pragma GCC diagnostic error "-Waggressive-loop-optimizations"

  #pragma GCC diagnostic error "-Wanalyzer-allocation-size"
  #pragma GCC diagnostic error "-Wanalyzer-deref-before-check"
  #pragma GCC diagnostic error "-Wanalyzer-double-fclose"
  #pragma GCC diagnostic error "-Wanalyzer-double-free"
  #pragma GCC diagnostic error "-Wanalyzer-exposure-through-output-file"
  #pragma GCC diagnostic error "-Wanalyzer-exposure-through-uninit-copy"
  #pragma GCC diagnostic error "-Wanalyzer-fd-access-mode-mismatch"
  #pragma GCC diagnostic error "-Wanalyzer-fd-double-close"
  #pragma GCC diagnostic error "-Wanalyzer-fd-leak"
  #pragma GCC diagnostic error "-Wanalyzer-fd-phase-mismatch"
  #pragma GCC diagnostic error "-Wanalyzer-fd-type-mismatch"
  #pragma GCC diagnostic error "-Wanalyzer-fd-use-after-close"
  #pragma GCC diagnostic error "-Wanalyzer-fd-use-without-check"
  #pragma GCC diagnostic error "-Wanalyzer-file-leak"
  #pragma GCC diagnostic error "-Wanalyzer-free-of-non-heap"
  #pragma GCC diagnostic error "-Wanalyzer-imprecise-fp-arithmetic"
  #pragma GCC diagnostic error "-Wanalyzer-infinite-loop"
  #pragma GCC diagnostic error "-Wanalyzer-infinite-recursion"
  #pragma GCC diagnostic error "-Wanalyzer-jump-through-null"
  #pragma GCC diagnostic error "-Wanalyzer-malloc-leak"
  #pragma GCC diagnostic error "-Wanalyzer-mismatching-deallocation"
  #pragma GCC diagnostic error "-Wanalyzer-null-argument"
  #pragma GCC diagnostic error "-Wanalyzer-null-dereference"
  #pragma GCC diagnostic error "-Wanalyzer-out-of-bounds"
  #pragma GCC diagnostic error "-Wanalyzer-overlapping-buffers"
  #pragma GCC diagnostic error "-Wanalyzer-possible-null-argument"
  #pragma GCC diagnostic error "-Wanalyzer-possible-null-dereference"
  #pragma GCC diagnostic error "-Wanalyzer-putenv-of-auto-var"
  #pragma GCC diagnostic error "-Wanalyzer-shift-count-negative"
  #pragma GCC diagnostic error "-Wanalyzer-shift-count-overflow"
  #pragma GCC diagnostic error "-Wanalyzer-stale-setjmp-buffer"
  #pragma GCC diagnostic error "-Wanalyzer-tainted-allocation-size"
  #pragma GCC diagnostic error "-Wanalyzer-tainted-array-index"
  #pragma GCC diagnostic error "-Wanalyzer-tainted-assertion"
  #pragma GCC diagnostic error "-Wanalyzer-tainted-divisor"
  #pragma GCC diagnostic error "-Wanalyzer-tainted-offset"
  #pragma GCC diagnostic error "-Wanalyzer-tainted-size"
  #pragma GCC diagnostic error "-Wanalyzer-throw-of-unexpected-type"
  #pragma GCC diagnostic error "-Wanalyzer-undefined-behavior-ptrdiff"
  #pragma GCC diagnostic error "-Wanalyzer-undefined-behavior-strtok"
  #pragma GCC diagnostic error "-Wanalyzer-unsafe-call-within-signal-handler"
  #pragma GCC diagnostic error "-Wanalyzer-use-after-free"
  #pragma GCC diagnostic error "-Wanalyzer-use-of-pointer-in-stale-stack-frame"
  #pragma GCC diagnostic error "-Wanalyzer-use-of-uninitialized-value"
  #pragma GCC diagnostic error "-Wanalyzer-va-arg-type-mismatch"
  #pragma GCC diagnostic error "-Wanalyzer-va-list-exhausted"
  #pragma GCC diagnostic error "-Wanalyzer-va-list-leak"
  #pragma GCC diagnostic error "-Wanalyzer-va-list-use-after-va-end"
  #pragma GCC diagnostic error "-Wanalyzer-write-to-const"
  #pragma GCC diagnostic error "-Wanalyzer-write-to-string-literal"

  #pragma GCC diagnostic error "-Wattribute-alias"
  #pragma GCC diagnostic error "-Wattribute-warning"
  #pragma GCC diagnostic error "-Wattributes"
  #pragma GCC diagnostic error "-Wbidi-chars"
  #pragma GCC diagnostic error "-Wbuiltin-declaration-mismatch"
  #pragma GCC diagnostic error "-Wbuiltin-macro-redefined"
  #pragma GCC diagnostic error "-Wcannot-profile"
  #pragma GCC diagnostic error "-Wcompare-distinct-pointer-types"
  #pragma GCC diagnostic error "-Wcomplain-wrong-lang"
  #pragma GCC diagnostic error "-Wcoverage-invalid-line-number"
  #pragma GCC diagnostic error "-Wcoverage-mismatch"
  #pragma GCC diagnostic error "-Wcoverage-too-many-conditions"
  #pragma GCC diagnostic error "-Wcoverage-too-many-paths"
  #pragma GCC diagnostic error "-Wcpp"
  #pragma GCC diagnostic error "-Wdeclaration-missing-parameter-type"
  #pragma GCC diagnostic error "-Wdeprecated"
  #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
  #pragma GCC diagnostic error "-Wdeprecated-openmp"
  #pragma GCC diagnostic error "-Wdesignated-init"
  #pragma GCC diagnostic error "-Wdiscarded-array-qualifiers"
  #pragma GCC diagnostic error "-Wdiscarded-qualifiers"
  #pragma GCC diagnostic error "-Wdiv-by-zero"
  #pragma GCC diagnostic error "-Wendif-labels"
  #pragma GCC diagnostic error "-Wfree-nonheap-object"
  #pragma GCC diagnostic error "-Whardened"
  #pragma GCC diagnostic error "-Wif-not-aligned"
  #pragma GCC diagnostic error "-Wignored-attributes"
  #pragma GCC diagnostic error "-Wincompatible-pointer-types"
  #pragma GCC diagnostic error "-Wint-conversion"
  #pragma GCC diagnostic error "-Wint-to-pointer-cast"
  #pragma GCC diagnostic error "-Winvalid-memory-model"
  #pragma GCC diagnostic error "-Wlto-type-mismatch"
  #pragma GCC diagnostic error "-Wmissing-profile"
  #pragma GCC diagnostic error "-Wmusttail-local-addr"
  #pragma GCC diagnostic error "-Wnormalized"
  #pragma GCC diagnostic error "-Wodr"
  #pragma GCC diagnostic error "-Wopenmp"
  #pragma GCC diagnostic error "-Woverflow"
  #pragma GCC diagnostic error "-Woverride-init-side-effects"
  #pragma GCC diagnostic error "-Wpointer-compare"
  #pragma GCC diagnostic error "-Wpointer-to-int-cast"
  #pragma GCC diagnostic error "-Wpragma-once-outside-header"
  #pragma GCC diagnostic error "-Wpragmas"
  #pragma GCC diagnostic error "-Wprio-ctor-dtor"
  #pragma GCC diagnostic error "-Wpsabi"
  #pragma GCC diagnostic error "-Wreturn-local-addr"
  #pragma GCC diagnostic error "-Wreturn-mismatch"
  #pragma GCC diagnostic error "-Wscalar-storage-order"
  #pragma GCC diagnostic error "-Wshift-count-negative"
  #pragma GCC diagnostic error "-Wshift-count-overflow"
  #pragma GCC diagnostic error "-Wsizeof-array-argument"
  #pragma GCC diagnostic error "-Wstringop-overread"
  #pragma GCC diagnostic error "-Wswitch-outside-range"
  #pragma GCC diagnostic error "-Wswitch-unreachable"
  #pragma GCC diagnostic error "-Wsync-nand"
  #pragma GCC diagnostic error "-Wtsan"
  #pragma GCC diagnostic error "-Wunicode"
  #pragma GCC diagnostic error "-Wunused-result"
  #pragma GCC diagnostic error "-Wvarargs"
  #pragma GCC diagnostic error "-Wxor-used-as-pow"
#endif

#if CC_CLANG
  #pragma clang diagnostic error "-Weverything"

  #pragma clang diagnostic ignored "-Wassign-enum"
  #pragma clang diagnostic ignored "-Wc++-keyword"
  #pragma clang diagnostic ignored "-Wc++98-compat"
  #pragma clang diagnostic ignored "-Wcast-function-type-strict"
  #pragma clang diagnostic ignored "-Wcast-qual"
  #pragma clang diagnostic ignored "-Wchar-subscripts"
  #pragma clang diagnostic ignored "-Wconstant-logical-operand"
  #pragma clang diagnostic ignored "-Wcovered-switch-default"
  #pragma clang diagnostic ignored "-Wdisabled-macro-expansion"
  #pragma clang diagnostic ignored "-Wfloat-equal"
  #pragma clang diagnostic ignored "-Wformat-nonliteral"
  #pragma clang diagnostic ignored "-Wimplicit-int-enum-cast"
  #pragma clang diagnostic ignored "-Wimplicit-void-ptr-cast"
  #pragma clang diagnostic ignored "-Wnrvo"
  #pragma clang diagnostic ignored "-Wpadded"
  #pragma clang diagnostic ignored "-Wpre-c11-compat"
  #pragma clang diagnostic ignored "-Wtentative-definition-compat"
  #pragma clang diagnostic warning "-Wunknown-warning-option"
  #pragma clang diagnostic ignored "-Wunsafe-buffer-usage"
  #pragma clang diagnostic ignored "-Wunused-macros"
  #pragma clang diagnostic ignored "-Wused-but-marked-unused"
  #pragma clang diagnostic ignored "-Wdeprecated-declarations"
#endif

#if DEBUGGING || TESTING
  #if CC_GCC || CC_CLANG
    #pragma GCC diagnostic ignored "-Wunused-function"
  #endif
#endif

#endif /* WARNINGS_H */
