#if !defined(WARNINGS_H)
#define WARNINGS_H

#include "platform_detection.h"

#if !defined(DEBUGGING)
#define DEBUGGING 0
#endif

#if !defined(TESTING)
#define TESTING 0
#endif

#if CBASE_CRT_MSVC
  #pragma warning(push, 4)
#endif

#if CC_GCC
  // -Wall
  #pragma GCC diagnostic warning "-Waddress"
  #pragma GCC diagnostic warning "-Warray-bounds"
  #pragma GCC diagnostic warning "-Wbool-compare"
  #pragma GCC diagnostic warning "-Wbool-operation"
  #pragma GCC diagnostic warning "-Wchar-subscripts"
  #pragma GCC diagnostic warning "-Wcomment"
  #pragma GCC diagnostic warning "-Wformat"
  #pragma GCC diagnostic warning "-Wformat-overflow"
  #pragma GCC diagnostic warning "-Wformat-truncation"
  #pragma GCC diagnostic warning "-Wint-in-bool-context"
  #pragma GCC diagnostic warning "-Wlogical-not-parentheses"
  #pragma GCC diagnostic warning "-Wmain"
  #pragma GCC diagnostic warning "-Wmaybe-uninitialized"
  #pragma GCC diagnostic warning "-Wmemset-elt-size"
  #pragma GCC diagnostic warning "-Wmemset-transposed-args"
  #pragma GCC diagnostic warning "-Wmisleading-indentation"
  #pragma GCC diagnostic warning "-Wmissing-attributes"
  #pragma GCC diagnostic warning "-Wmissing-braces"
  #pragma GCC diagnostic warning "-Wmultistatement-macros"
  #pragma GCC diagnostic warning "-Wnonnull"
  #pragma GCC diagnostic warning "-Wnonnull-compare"
  #pragma GCC diagnostic warning "-Wparentheses"
  #pragma GCC diagnostic warning "-Wpointer-sign"
  #pragma GCC diagnostic warning "-Wrestrict"
  #pragma GCC diagnostic warning "-Wreturn-type"
  #pragma GCC diagnostic warning "-Wsequence-point"
  #pragma GCC diagnostic warning "-Wsizeof-pointer-div"
  #pragma GCC diagnostic warning "-Wsizeof-pointer-memaccess"
  #pragma GCC diagnostic warning "-Wstrict-aliasing"
  #pragma GCC diagnostic warning "-Wstrict-overflow"
  #pragma GCC diagnostic warning "-Wstringop-overflow"
  #pragma GCC diagnostic warning "-Wstringop-truncation"
  #pragma GCC diagnostic warning "-Wswitch"
  #pragma GCC diagnostic warning "-Wswitch-bool"
  #pragma GCC diagnostic warning "-Wtautological-compare"
  #pragma GCC diagnostic warning "-Wtrigraphs"
  #pragma GCC diagnostic warning "-Wuninitialized"
  #pragma GCC diagnostic warning "-Wunknown-pragmas"
  #pragma GCC diagnostic warning "-Wunused-function"
  #pragma GCC diagnostic warning "-Wunused-label"
  #pragma GCC diagnostic warning "-Wunused-value"
  #pragma GCC diagnostic warning "-Wunused-variable"
  #pragma GCC diagnostic warning "-Wvolatile-register-var"

  // -Wextra
  #pragma GCC diagnostic warning "-Wclobbered"
  #pragma GCC diagnostic warning "-Wcast-function-type"
  #pragma GCC diagnostic warning "-Wempty-body"
  #pragma GCC diagnostic warning "-Wignored-qualifiers"
  #pragma GCC diagnostic warning "-Wimplicit-fallthrough"
  #pragma GCC diagnostic warning "-Wmissing-field-initializers"
  #pragma GCC diagnostic warning "-Wmissing-parameter-type"
  #pragma GCC diagnostic warning "-Wold-style-declaration"
  #pragma GCC diagnostic warning "-Woverride-init"
  #pragma GCC diagnostic warning "-Wsign-compare"
  #pragma GCC diagnostic warning "-Wstring-compare"
  #pragma GCC diagnostic warning "-Wtype-limits"
  #pragma GCC diagnostic warning "-Wshift-negative-value"
  #pragma GCC diagnostic warning "-Wunused-parameter"
  #pragma GCC diagnostic warning "-Wunused-but-set-parameter"

  // Enabled by default or not enabled -Wall or -Wextra
  #pragma GCC diagnostic warning "-WNSObject-attribute"
  #pragma GCC diagnostic warning "-Waddress-of-packed-member"
  #pragma GCC diagnostic warning "-Waggressive-loop-optimizations"

  #pragma GCC diagnostic warning "-Wanalyzer-allocation-size"
  #pragma GCC diagnostic warning "-Wanalyzer-deref-before-check"
  #pragma GCC diagnostic warning "-Wanalyzer-double-fclose"
  #pragma GCC diagnostic warning "-Wanalyzer-double-free"
  #pragma GCC diagnostic warning "-Wanalyzer-exposure-through-output-file"
  #pragma GCC diagnostic warning "-Wanalyzer-exposure-through-uninit-copy"
  #pragma GCC diagnostic warning "-Wanalyzer-fd-access-mode-mismatch"
  #pragma GCC diagnostic warning "-Wanalyzer-fd-double-close"
  #pragma GCC diagnostic warning "-Wanalyzer-fd-leak"
  #pragma GCC diagnostic warning "-Wanalyzer-fd-phase-mismatch"
  #pragma GCC diagnostic warning "-Wanalyzer-fd-type-mismatch"
  #pragma GCC diagnostic warning "-Wanalyzer-fd-use-after-close"
  #pragma GCC diagnostic warning "-Wanalyzer-fd-use-without-check"
  #pragma GCC diagnostic warning "-Wanalyzer-file-leak"
  #pragma GCC diagnostic warning "-Wanalyzer-free-of-non-heap"
  #pragma GCC diagnostic warning "-Wanalyzer-imprecise-fp-arithmetic"
  #pragma GCC diagnostic warning "-Wanalyzer-infinite-loop"
  #pragma GCC diagnostic warning "-Wanalyzer-infinite-recursion"
  #pragma GCC diagnostic warning "-Wanalyzer-jump-through-null"
  #pragma GCC diagnostic warning "-Wanalyzer-malloc-leak"
  #pragma GCC diagnostic warning "-Wanalyzer-mismatching-deallocation"
  #pragma GCC diagnostic warning "-Wanalyzer-null-argument"
  #pragma GCC diagnostic warning "-Wanalyzer-null-dereference"
  #pragma GCC diagnostic warning "-Wanalyzer-out-of-bounds"
  #pragma GCC diagnostic warning "-Wanalyzer-overlapping-buffers"
  #pragma GCC diagnostic warning "-Wanalyzer-possible-null-argument"
  #pragma GCC diagnostic warning "-Wanalyzer-possible-null-dereference"
  #pragma GCC diagnostic warning "-Wanalyzer-putenv-of-auto-var"
  #pragma GCC diagnostic warning "-Wanalyzer-shift-count-negative"
  #pragma GCC diagnostic warning "-Wanalyzer-shift-count-overflow"
  #pragma GCC diagnostic warning "-Wanalyzer-stale-setjmp-buffer"
  #pragma GCC diagnostic warning "-Wanalyzer-tainted-allocation-size"
  #pragma GCC diagnostic warning "-Wanalyzer-tainted-array-index"
  #pragma GCC diagnostic warning "-Wanalyzer-tainted-assertion"
  #pragma GCC diagnostic warning "-Wanalyzer-tainted-divisor"
  #pragma GCC diagnostic warning "-Wanalyzer-tainted-offset"
  #pragma GCC diagnostic warning "-Wanalyzer-tainted-size"
  #pragma GCC diagnostic warning "-Wanalyzer-throw-of-unexpected-type"
  #pragma GCC diagnostic warning "-Wanalyzer-undefined-behavior-ptrdiff"
  #pragma GCC diagnostic warning "-Wanalyzer-undefined-behavior-strtok"
  #pragma GCC diagnostic warning "-Wanalyzer-unsafe-call-within-signal-handler"
  #pragma GCC diagnostic warning "-Wanalyzer-use-after-free"
  #pragma GCC diagnostic warning "-Wanalyzer-use-of-pointer-in-stale-stack-frame"
  #pragma GCC diagnostic warning "-Wanalyzer-use-of-uninitialized-value"
  #pragma GCC diagnostic warning "-Wanalyzer-va-arg-type-mismatch"
  #pragma GCC diagnostic warning "-Wanalyzer-va-list-exhausted"
  #pragma GCC diagnostic warning "-Wanalyzer-va-list-leak"
  #pragma GCC diagnostic warning "-Wanalyzer-va-list-use-after-va-end"
  #pragma GCC diagnostic warning "-Wanalyzer-write-to-const"
  #pragma GCC diagnostic warning "-Wanalyzer-write-to-string-literal"

  #pragma GCC diagnostic warning "-Wattribute-alias"
  #pragma GCC diagnostic warning "-Wattribute-warning"
  #pragma GCC diagnostic warning "-Wattributes"
  #pragma GCC diagnostic warning "-Wbidi-chars"
  #pragma GCC diagnostic warning "-Wbuiltin-declaration-mismatch"
  #pragma GCC diagnostic warning "-Wbuiltin-macro-redefined"
  #pragma GCC diagnostic warning "-Wcannot-profile"
  #pragma GCC diagnostic warning "-Wcompare-distinct-pointer-types"
  #pragma GCC diagnostic warning "-Wcomplain-wrong-lang"
  #pragma GCC diagnostic warning "-Wcoverage-invalid-line-number"
  #pragma GCC diagnostic warning "-Wcoverage-mismatch"
  #pragma GCC diagnostic warning "-Wcoverage-too-many-conditions"
  #pragma GCC diagnostic warning "-Wcoverage-too-many-paths"
  #pragma GCC diagnostic warning "-Wcpp"
  #pragma GCC diagnostic warning "-Wdeclaration-missing-parameter-type"
  #pragma GCC diagnostic warning "-Wdeprecated"
  #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
  #pragma GCC diagnostic warning "-Wdeprecated-openmp"
  #pragma GCC diagnostic warning "-Wdesignated-init"
  #pragma GCC diagnostic warning "-Wdiscarded-array-qualifiers"
  #pragma GCC diagnostic warning "-Wdiscarded-qualifiers"
  #pragma GCC diagnostic warning "-Wdiv-by-zero"
  #pragma GCC diagnostic warning "-Wendif-labels"
  #pragma GCC diagnostic warning "-Wfree-nonheap-object"
  #pragma GCC diagnostic warning "-Whardened"
  #pragma GCC diagnostic warning "-Wif-not-aligned"
  #pragma GCC diagnostic warning "-Wignored-attributes"
  #pragma GCC diagnostic warning "-Wincompatible-pointer-types"
  #pragma GCC diagnostic warning "-Wint-conversion"
  #pragma GCC diagnostic warning "-Wint-to-pointer-cast"
  #pragma GCC diagnostic warning "-Winvalid-memory-model"
  #pragma GCC diagnostic warning "-Wlto-type-mismatch"
  #pragma GCC diagnostic warning "-Wmissing-profile"
  #pragma GCC diagnostic warning "-Wmusttail-local-addr"
  #pragma GCC diagnostic warning "-Wnormalized"
  #pragma GCC diagnostic warning "-Wodr"
  #pragma GCC diagnostic warning "-Wopenmp"
  #pragma GCC diagnostic warning "-Woverflow"
  #pragma GCC diagnostic warning "-Woverride-init-side-effects"
  #pragma GCC diagnostic warning "-Wpointer-compare"
  #pragma GCC diagnostic warning "-Wpointer-to-int-cast"
  #pragma GCC diagnostic warning "-Wpragma-once-outside-header"
  #pragma GCC diagnostic warning "-Wpragmas"
  #pragma GCC diagnostic warning "-Wprio-ctor-dtor"
  #pragma GCC diagnostic warning "-Wpsabi"
  #pragma GCC diagnostic warning "-Wreturn-local-addr"
  #pragma GCC diagnostic warning "-Wreturn-mismatch"
  #pragma GCC diagnostic warning "-Wscalar-storage-order"
  #pragma GCC diagnostic warning "-Wshift-count-negative"
  #pragma GCC diagnostic warning "-Wshift-count-overflow"
  #pragma GCC diagnostic warning "-Wsizeof-array-argument"
  #pragma GCC diagnostic warning "-Wstringop-overread"
  #pragma GCC diagnostic warning "-Wswitch-outside-range"
  #pragma GCC diagnostic warning "-Wswitch-unreachable"
  #pragma GCC diagnostic warning "-Wsync-nand"
  #pragma GCC diagnostic warning "-Wtsan"
  #pragma GCC diagnostic warning "-Wunicode"
  #pragma GCC diagnostic warning "-Wunused-result"
  #pragma GCC diagnostic warning "-Wvarargs"
  #pragma GCC diagnostic warning "-Wxor-used-as-pow"
#endif

#if CC_CLANG
  #pragma clang diagnostic warning "-Weverything"

  #pragma clang diagnostic ignored "-Wassign-enum"
  #pragma clang diagnostic ignored "-Wc++-keyword"
  #pragma clang diagnostic ignored "-Wc++98-compat"
  #pragma clang diagnostic ignored "-Wcast-function-type-strict"
  #pragma clang diagnostic ignored "-Wcast-qual"
  #pragma clang diagnostic ignored "-Wchar-subscripts"
  #pragma clang diagnostic ignored "-Wconstant-logical-operand"
  #pragma clang diagnostic ignored "-Wcovered-switch-default"
  #pragma clang diagnostic ignored "-Wdisabled-macro-expansion"
  #pragma clang diagnostic ignored "-Wfloat-equal"
  #pragma clang diagnostic ignored "-Wformat-nonliteral"
  #pragma clang diagnostic ignored "-Wimplicit-int-enum-cast"
  #pragma clang diagnostic ignored "-Wimplicit-void-ptr-cast"
  #pragma clang diagnostic ignored "-Wnrvo"
  #pragma clang diagnostic ignored "-Wpadded"
  #pragma clang diagnostic ignored "-Wpre-c11-compat"
  #pragma clang diagnostic ignored "-Wtentative-definition-compat"
  #pragma clang diagnostic warning "-Wunknown-warning-option"
  #pragma clang diagnostic ignored "-Wunsafe-buffer-usage"
  #pragma clang diagnostic ignored "-Wunused-macros"
  #pragma clang diagnostic ignored "-Wused-but-marked-unused"
  #pragma clang diagnostic ignored "-Wdeprecated-declarations"
#endif

#if DEBUGGING || TESTING
  #if CC_GCC || CC_CLANG
    #pragma GCC diagnostic ignored "-Wunused-function"
  #endif
#endif

#endif /* WARNINGS_H */
